//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterMindApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games_Stages
    {
        public int Games_StagesId { get; set; }
        public Nullable<int> GameId { get; set; }
        public Nullable<int> StageId { get; set; }
    }
}
