//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterMindApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games
    {
        public int GameId { get; set; }
        public string GameSequence { get; set; }
        public Nullable<int> Winner_UserId { get; set; }
        public Nullable<int> Player_Games_StagesId1 { get; set; }
        public Nullable<int> Player_Games_StagesId2 { get; set; }
        public string Player_Name_1 { get; set; }
        public string Player_Name_2 { get; set; }
    }
}
