//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterMindApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stages
    {
        public int StageId { get; set; }
        public string PlayerSequence { get; set; }
        public string StageCheck { get; set; }
        public Nullable<int> IsMatch { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> GameId { get; set; }
        public string StageCheck2 { get; set; }
    }
}
